# This workflow is used to auto-create ADO work items for new PRs.

name: Track new PRs on ADO
on:
  pull_request_target:
    types:
      - opened
jobs:
  create_ado_item:
    name: Create an ADO work item for new PRs
    runs-on: ubuntu-latest
    steps:
      - uses: captainbrosset/github-actions-issue-to-work-item@simple-sync
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
        with:
          ado_organization: 'microsoft'
          ado_project: 'Edge'
          ado_tags: 'edge-docs-github-pr'
          ado_area_path: 'Edge\Web Experience\Ecosystem\Content'
          ado_work_item_type: 'Deliverable'
          ado_dont_check_if_exist: true
