# This workflow is used to auto-create ADO work items when issues are labeled with ADO.

name: Track newly labeled issues on ADO
on:
  issues:
    types:
      [labeled]
jobs:
  create_ado_item:
    name: Create an ADO work item for labeled issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: MicrosoftEdge/action-issue-to-workitem@main
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
        with:
          label: 'ADO'
          ado_organization: 'microsoft'
          ado_project: 'Edge'
          ado_tags: 'edge-docs-github-issue'
          ado_area_path: 'Edge\Web Experience\Ecosystem\Content'
          ado_work_item_type: 'Deliverable'
          ado_product: 'Documentation'
