# This workflow is used to add the 'triage-needed' label to newly opened issues.
# This way it's easy for us to know which issues have not been triaged yet.

name: Label new issues to be triaged
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          add-labels: "triage-needed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}