name: "New issue labeler"
on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@e24a3eb6b2e28c8904d086302a2b760647f5f45c # v3.1
      with:
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
        repo-token: ${{ github.token }}