name: ESLint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint