# This workflow looks for references to old Edge versions in the docs.
# When outdated versions are found, an issue is created.

name: Find outdated versions

on:
  workflow_dispatch:
  schedule:
    # once a month
    - cron: '0 0 1 * *'

jobs:
  check-old-versions:
    name: Check for references of old versions of Edge
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd scripts
          npm install
      - name: Run script
        id: findversions
        run: |
          cd scripts
          token=${{ secrets.GITHUB_TOKEN }} node report-references-to-old-versions.js
