# This workflow looks for references to old Edge versions in the docs.
# When outdated versions are found, an issue is created.

name: Find outdated versions

on:
  workflow_dispatch:
  schedule:
    # once a month
    - cron: '0 0 1 * *'

jobs:
  check-old-versions:
    name: Check for references of old versions of Edge
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd scripts
          npm install
      - name: Run script
        id: findversions
        run: |
          cd scripts
          token=${{ secrets.GITHUB_TOKEN }} node report-references-to-old-versions.js
