# This workflow looks for references to old Edge versions in the docs.
# When outdated versions are found, an issue is created.

name: Find outdated versions

on:
  workflow_dispatch:
  schedule:
    # once a month
    - cron: '0 0 1 * *'

jobs:
  check-old-versions:
    name: Check for references of old versions of Edge
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd scripts
          npm install
      - name: Run script
        id: findversions
        run: |
          cd scripts
          token=${{ secrets.GITHUB_TOKEN }} node report-references-to-old-versions.js
