# This workflow checks if it's time to generate the next beta relnotes.
# And if so, it generates a draft and opens an issue to notify the team.

name: Generate beta relnotes

on:
  workflow_dispatch:
  schedule:
    # once a day
    - cron: '0 0 * * *'

permissions:
  contents: write
  issues: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd scripts
          npm install
          npx playwright install

      - name: Generate release notes
        run: |
          cd scripts
          token=${{ secrets.GITHUB_TOKEN }} node web-platform-release-notes.js

      - name: Commit changes if needed
        run: |
          files=$(git ls-files --others --exclude-standard)
          if [ -n "$files" ]; then
              echo "Committing the new release notes file."
              git config --local user.email "${{ github.actor }}@users.noreply.github.com"
              git config --local user.name "${{ github.actor }}"
              git checkout -b web-platform-release-notes
              git add .
              git commit -m "New beta web platform release notes"
              git push origin web-platform-release-notes
          else
              echo "No new files to add."
          fi
